version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bookwormshop-products-db
    environment:
      POSTGRES_USER: bookworm
      POSTGRES_PASSWORD: bookworm
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
